# Generated by Django 4.1.5 on 2023-02-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_by',
            field=models.CharField(default='jooda', max_length=50),
            preserve_default=False,
        ),
    ]
